# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Docker image to Azure Web App - front-sai

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ignacio121/build-front-sai:${{ github.sha }} .
        docker push ignacio121/build-front-sai:${{ github.sha }} 

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'front-sai'
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        images: 'ignacio121/build-front-sai:${{ github.sha }}'
